<?php

require_once 'C:\Users\Zach\workspace\LegoLabCellGui\DefectTableObject.php';

/**
 * Test class for DefectTableObject.
 * Generated by PHPUnit on 2013-04-18 at 14:17:40.
 */
class DefectTableObjectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DefectTableObject
     */
    protected $defectTableObject;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->defectTableObject = new DefectTableObject();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DefectTableObject::getDefects
     */
    public function testGetDefects()
    {
        $this->assertEquals(0, $this->defectTableObject->getDefects());
    }

    /**
     * @covers DefectTableObject::setDefects
     * @todo Implement testSetDefects().
     */
    public function testSetDefects()
    {
    	$newDefects = 3;
        $this->defectTableObject->setDefects($newDefects);
        $this->assertEquals($newDefects, $this->defectTableObject->getDefects());
    }
}
?>
