<?php

require_once 'C:\Users\Zach\workspace\LegoLabCellGui\DefectFileReader.php';

/**
 * Test class for DefectFileReader.
 * Generated by PHPUnit on 2013-04-18 at 12:27:30.
 */
class DefectFileReaderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DefectFileReader
     */
    protected $fileReader;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    	date_default_timezone_set('America/Chicago');
    	$fileName = 'Station1DefectResults-' . date('Ymd') . 'T' . date('His');
    	$handle = fopen($fileName, 'w');
    	fwrite($handle, "1 2,3");
    	fclose($handle);
    	$this->fileReader = new DefectFileReader($fileName);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DefectFileReader::extractData
     */
    public function testExtractData()
    {
    	$string = "1 2,3";
        $stringArray = $this->fileReader->extractData($string);
        $this->assertEquals(array("1", "2,3"), $stringArray[0]);
    }
}
?>
