<?php

require_once 'C:\Users\Zach\workspace\LegoLabCellGui\DefectFileReader.php';

/**
 * Test class for FileReader.
 * Generated by PHPUnit on 2013-04-18 at 11:16:31.
 */
class FileReaderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FileReader
     */
    protected $fileReader;
    protected $fileName;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    	date_default_timezone_set('America/Chicago');
    	$this->fileName = 'Station1DefectResults-' . date('Ymd') . 'T' . date('His');
    	$handle = fopen($this->fileName, 'w');
    	fwrite($handle, "1 2,3");
    	fclose($handle);
    	$this->fileReader = new DefectFileReader($this->fileName);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FileReader::openFile
     */
    public function testOpenFile()
    {
    	$stringResult = $this->fileReader->openFile();
    	$this->assertEquals("1 2,3", $stringResult);
    }

    /**
     * @covers FileReader::setFilename
     */
    public function testSetFilename()
    {
    	$newFileName = "Station2DefectResults-" . date('Ymd') . 'T' . date('His');
        $this->fileReader->setFileName($newFileName);
        $this->assertEquals($newFileName, $this->fileReader->getFileName());
    }

    /**
     * @covers FileReader::getFilename
     */
    public function testGetFilename()
    {
        $this->assertEquals($this->fileName, $this->fileReader->getFileName());
    }
}
?>
