<?php

require_once 'C:\Users\Zach\workspace\LegoLabCellGui\OverallInformation.php';

/**
 * Test class for OverallInformation.
 * Generated by PHPUnit on 2013-04-18 at 15:58:47.
 */
class OverallInformationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var OverallInformation
     */
    protected $overallInformation;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    	$newStationsPerCell = 5;
    	$newTableWriter = new TableWriter();
    	$newGrapher = new Grapher();
        $this->overallInformation = new OverallInformation($newStationsPerCell, $newTableWriter, $newGrapher);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers OverallInformation::updateAverageProcessTime
     * @todo Implement testUpdateAverageProcessTime().
     */
    public function testUpdateAverageProcessTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OverallInformation::updateAverageIdleTime
     * @todo Implement testUpdateAverageIdleTime().
     */
    public function testUpdateAverageIdleTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OverallInformation::updateBottleNeckStation
     * @todo Implement testUpdateBottleNeckStation().
     */
    public function testUpdateBottleNeckStation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OverallInformation::updateTotalTime
     * @todo Implement testUpdateTotalTime().
     */
    public function testUpdateTotalTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OverallInformation::updateStatus
     * @todo Implement testUpdateStatus().
     */
    public function testUpdateStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OverallInformation::updateDefectTimes
     * @todo Implement testUpdateDefectTimes().
     */
    public function testUpdateDefectTimes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OverallInformation::updateTotalDefectCount
     * @todo Implement testUpdateTotalDefectCount().
     */
    public function testUpdateTotalDefectCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OverallInformation::updateGraphs
     * @todo Implement testUpdateGraphs().
     */
    public function testUpdateGraphs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OverallInformation::addTimePoint
     * @todo Implement testAddTimePoint().
     */
    public function testAddTimePoint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
