<?php

require_once 'C:\Users\Zach\workspace\LegoLabCellGui\DefectTableObject.php';

/**
 * Test class for TableObject.
 * Generated by PHPUnit on 2013-04-18 at 13:42:00.
 */
class TableObjectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TableObject
     */
    protected $defectTableObject;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->defectTableObject = new TableObject();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TableObject::getCellNumber
     */
    public function testGetCellNumber()
    {
        $this->assertEquals(0, $this->defectTableObject->getCellNumber());
    }

    /**
     * @covers TableObject::getFileTime
     */
    public function testGetFileTime()
    {
        $this->assertEquals(0, $this->defectTableObject->getFileTime());
    }

    /**
     * @covers TableObject::getSensorNumber
     */
    public function testGetSensorNumber()
    {
        $this->assertEquals(0, $this->defectTableObject->getSensorNumber());
    }

    /**
     * @covers TableObject::setCellNumber
     */
    public function testSetCellNumber()
    {
    	$newCellNumber = 1;
        $this->defectTableObject->setCellNumber($newCellNumber);
        $this->assertEquals($newCellNumber, $this->defectTableObject->getCellNumber());
    }

    /**
     * @covers TableObject::setFileTime
     */
    public function testSetFileTime()
    {
        $newFileTime = 43;
        $this->defectTableObject->setFileTime($newFileTime);
        $this->assertEquals($newFileTime, $this->defectTableObject->getFileTime());
    }

    /**
     * @covers TableObject::setSensorNumber
     * @todo Implement testSetSensorNumber().
     */
    public function testSetSensorNumber()
    {
        $newSensorNumber = 4;
        $this->defectTableObject->setSensorNumber($newSensorNumber);
        $this->assertEquals($newSensorNumber, $this->defectTableObject->getSensorNumber());
    }
}
?>
