<?php

require_once 'C:\Users\Zach\workspace\LegoLabCellGui\TimeTableObject.php';

/**
 * Test class for TimeTableObject.
 * Generated by PHPUnit on 2013-04-18 at 15:35:55.
 */
class TimeTableObjectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TimeTableObject
     */
    protected $timeTableObject;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->timeTableObject = new TimeTableObject();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TimeTableObject::getOnTime
     */
    public function testGetOnTime()
    {
        $this->assertEquals(0, $this->timeTableObject->getOnTime());
    }

    /**
     * @covers TimeTableObject::getOffTime
     * @todo Implement testGetOffTime().
     */
    public function testGetOffTime()
    {
        $this->assertEquals(0, $this->timeTableObject->getOffTime());
    }

    /**
     * @covers TimeTableObject::setOnTime
     */
    public function testSetOnTime()
    {
    	$newOnTime = 35;
        $this->timeTableObject->setOnTime($newOnTime);
        $this->assertEquals($newOnTime, $this->timeTableObject->getOnTime());
    }

    /**
     * @covers TimeTableObject::setOffTime
     */
    public function testSetOffTime()
    {
        $newOffTime = 43;
        $this->timeTableObject->setOffTime($newOffTime);
        $this->assertEquals($newOffTime, $this->timeTableObject->getOffTime());
    }
}
?>
