<?php

require_once 'C:\Users\Zach\workspace\LegoLabCellGui\TimeFileReader.php';

/**
 * Test class for TimeFileReader.
 * Generated by PHPUnit on 2013-04-18 at 15:41:20.
 */
class TimeFileReaderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TimeFileReader
     */
    protected $timeFileReader;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        date_default_timezone_set('America/Chicago');
    	$fileName = 'Station1TimeData-' . date('Ymd') . 'T' . date('His');
    	$handle = fopen($fileName, 'w');
    	fwrite($handle, "27.54 31.78");
    	fclose($handle);
    	$this->fileReader = new TimeFileReader($fileName);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TimeFileReader::extractData
     * @todo Implement testExtractData().
     */
    public function testExtractData()
    {
        $string = "27.54 31.78";
        $stringArray = $this->fileReader->extractData($string);
        $this->assertEquals(array("27.54", "31.78"), $stringArray[0]);
    }
}
?>
